/**
 * OpenAgentFlow — Isolated Demo Helper Template Module
 *
 * This module generates self-contained Python code (`_DemoChatModel`, `_maybe_get_demo_llm`,
 * `_format_demo_state`) used strictly when `--demo` (OAF_DEMO=1) is active.
 *
 * It can be cleanly deleted from the codebase if demo simulation mode is ever removed.
 * See: llm/handover/2026-07-20-screencast-and-demo-removal-guide.md
 */

export function generateDemoHelperTemplate() {
  const lines = [
    `# ─── DEMO HOOK MODULE (Cleanly removable) ───────────────────────────────────`,
    `import hashlib, json, os`,
    `class _DemoChatModel:`,
    `    def __init__(self, model, temperature=0, provider="demo"):`,
    `        self.model = model`,
    `        self.temperature = temperature`,
    `        self._oaf_provider = provider`,
    ``,
    `    def invoke(self, messages, *args, **kwargs):`,
    `        cache_dir = os.path.join(os.path.expanduser("~"), ".oaf")`,
    `        cache_file = os.path.join(cache_dir, "demo_cache.json")`,
    `        prompt_parts = []`,
    `        sys_prompt = ""`,
    `        for m in messages:`,
    `            if isinstance(m, dict):`,
    `                role = m.get("role", "")`,
    `                content_str = str(m.get("content", ""))`,
    `                if role == "system": sys_prompt = content_str`,
    `                prompt_parts.append(f"{role}:{content_str}")`,
    `            elif hasattr(m, "type"):`,
    `                content_str = str(getattr(m, "content", ""))`,
    `                if m.type == "system": sys_prompt = content_str`,
    `                prompt_parts.append(f"{m.type}:{content_str}")`,
    `            else:`,
    `                prompt_parts.append(str(m))`,
    ``,
    `        full_prompt = "|".join(prompt_parts)`,
    `        cache_key = f"{self.model}:{hashlib.sha256(full_prompt.encode('utf-8')).hexdigest()}"`,
    ``,
    `        if os.path.exists(cache_file):`,
    `            try:`,
    `                with open(cache_file, "r", encoding="utf-8") as f:`,
    `                    cache_data = json.load(f)`,
    `                if cache_key in cache_data:`,
    `                    class _AIMessage:`,
    `                        def __init__(self, text): self.content = text`,
    `                    return _AIMessage(cache_data[cache_key])`,
    `            except Exception:`,
    `                pass`,
    ``,
    `        if "extract the most important facts" in sys_prompt.lower() or "extractor" in sys_prompt.lower():`,
    `            content = (`,
    `                "- Monolithic LLMs are transitioning to multi-agent pipelines where specialized agents handle distinct sub-tasks.\\n"`,
    `                "- Robust state management and clear communication protocols are critical to prevent information loss and infinite loops.\\n"`,
    `                "- Standardized open-source frameworks provide unified syntax and configurations, lowering the engineering barrier."`,
    `            )`,
    `        elif "weave them into a clear, cohesive summary" in sys_prompt.lower() or "synthesizer" in sys_prompt.lower():`,
    `            content = (`,
    `                "Modern AI is rapidly evolving from monolithic models to collaborative multi-agent pipelines where specialized models execute modular sub-tasks. "`,
    `                "While this approach improves reliability and performance, it introduces orchestration challenges requiring robust state management and structured communication protocols. "`,
    `                "Standardized open-source frameworks address these bottlenecks by offering a unified syntax and automated state coordination, making multi-agent deployment as seamless as containerizing a web application."`,
    `            )`,
    `        else:`,
    `            content = f"[Demo Output for {self.model}]: Successfully processed workflow input."`,
    ``,
    `        class _AIMessage:`,
    `            def __init__(self, text):`,
    `                self.content = text`,
    ``,
    `        try:`,
    `            os.makedirs(cache_dir, exist_ok=True)`,
    `            cache_data = {}`,
    `            if os.path.exists(cache_file):`,
    `                with open(cache_file, "r", encoding="utf-8") as f:`,
    `                    cache_data = json.load(f)`,
    `            cache_data[cache_key] = content`,
    `            with open(cache_file, "w", encoding="utf-8") as f:`,
    `                json.dump(cache_data, f, indent=2, ensure_ascii=False)`,
    `        except Exception:`,
    `            pass`,
    ``,
    `        return _AIMessage(content)`,
    ``,
    `def _maybe_get_demo_llm(target_model, temperature, target_provider):`,
    `    if os.environ.get("OAF_DEMO") == "1" or target_provider == "demo":`,
    `        return _DemoChatModel(model=target_model, temperature=temperature, provider=target_provider or "demo")`,
    `    return None`,
    ``,
    `def _format_demo_state(result, initial_state):`,
    `    if os.environ.get("OAF_DEMO") != "1":`,
    `        return result`,
    `    display_state = {}`,
    `    for k, v in result.items():`,
    `        if k in initial_state and isinstance(v, str) and len(v) > 100 and result[k] == initial_state[k]:`,
    `            display_state[k] = f"{v[:80]}... ({len(v)} chars abbreviated)"`,
    `        else:`,
    `            display_state[k] = v`,
    `    return display_state`,
    `# ────────────────────────────────────────────────────────────────────────────`,
  ];
  return lines.join('\n');
}
