/**
 * OpenAgentFlow — LangGraph Python Templates
 *
 * This module contains the reusable Python templates and runtime helper stubs
 * used by the LangGraph adapter. It has no knowledge of the OpenAgentFlow compiler,
 * IR parsing, or JavaScript implementation.
 */

/**
 * Generate the Python file header comment block.
 * @param {object} params
 * @param {string} params.workflowName
 * @param {string} params.version
 * @returns {string}
 */
export function generateHeaderTemplate({ workflowName, version }) {
  return [
    `"""`,
    `OpenAgentFlow — Generated LangGraph Workflow`,
    ``,
    `Workflow: ${workflowName}`,
    `Generated by: OpenAgentFlow Compiler v${version}`,
    ``,
    `This file was auto-generated from an .oaf workflow definition.`,
    `Do not edit manually — regenerate from the source .oaf file.`,
    `"""`,
    ``,
  ].join('\n');
}

/**
 * Generate Python imports block.
 * @param {object} params
 * @param {string[]} params.typingImports - Array of typing symbols (e.g. ['Dict', 'List', 'Optional', 'TypedDict'])
 * @param {boolean} params.needsLlmProviders - Whether to include provider import checks
 * @returns {string}
 */
export function generateImportsTemplate({ typingImports, needsLlmProviders, needsOperator }) {
  const lines = [
    `import os`,
    `import sys`,
    `import json`,
  ];

  if (needsOperator) {
    lines.push(`import operator`);
  }

  lines.push(`from typing import ${typingImports.sort().join(', ')}`);
  lines.push(``);
  lines.push(`from langgraph.graph import StateGraph, END`);

  if (needsLlmProviders) {
    lines.push(``);
    lines.push(`# LLM providers — Gemini is primary, OpenAI is fallback`);
    lines.push(`_LLM_PROVIDER = None`);
    lines.push(`try:`);
    lines.push(`    from langchain_google_genai import ChatGoogleGenerativeAI`);
    lines.push(`    if os.environ.get("GOOGLE_API_KEY"):`);
    lines.push(`        _LLM_PROVIDER = "gemini"`);
    lines.push(`except ImportError:`);
    lines.push(`    pass`);
    lines.push(``);
    lines.push(`if _LLM_PROVIDER is None:`);
    lines.push(`    try:`);
    lines.push(`        from langchain_openai import ChatOpenAI`);
    lines.push(`        if os.environ.get("OPENAI_API_KEY"):`);
    lines.push(`            _LLM_PROVIDER = "openai"`);
    lines.push(`    except ImportError:`);
    lines.push(`        pass`);
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Generate the WorkflowState TypedDict definition.
 * @param {object} params
 * @param {Array<{ name: string, pyType: string }>} params.fields
 * @returns {string}
 */
export function generateStateClassTemplate({ fields }) {
  const lines = [
    `# ─── State Schema ───────────────────────────────────────────────────────────`,
    ``,
    `class WorkflowState(TypedDict, total=False):`,
  ];

  if (!fields || fields.length === 0) {
    lines.push(`    pass`);
  } else {
    for (const field of fields) {
      const comment = field.required ? `  # @required` : '';
      const baseType = `Optional[${field.pyType}]`;
      const typeStr = field.reducer ? `Annotated[${baseType}, operator.add]` : baseType;
      lines.push(`    ${field.name}: ${typeStr}${comment}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Generate the runtime LLM helper (`get_llm`).
 * @param {object} params
 * @param {string|null} params.defaultModel
 * @param {number} params.defaultTemperature
 * @returns {string}
 */
export function generateLlmHelperTemplate({ defaultModel, defaultTemperature }) {
  const defaultModelArg = defaultModel != null ? `"${defaultModel}"` : `None`;
  const lines = [
    `# ─── LLM Helper ─────────────────────────────────────────────────────────────`,
    ``,
    `def get_llm(model: Optional[str] = ${defaultModelArg}, temperature: float = ${defaultTemperature}, provider: Optional[str] = None):`,
    `    """Get the LLM instance. Uses provided model directly; falls back to OAF_DEFAULT_MODEL or raises error."""`,
    `    target_model = model if model else os.environ.get("OAF_DEFAULT_MODEL")`,
    `    if not target_model:`,
    `        raise RuntimeError(`,
    `            "No model specified and no default model configured. "`,
    `            "Please specify a 'model' property in your .oaf agent definition or set the OAF_DEFAULT_MODEL environment variable."`,
    `        )`,
    ``,
    `    target_provider = provider if provider else _LLM_PROVIDER`,
    `    if target_provider == "gemini":`,
    `        return ChatGoogleGenerativeAI(model=target_model, temperature=temperature)`,
    `    elif target_provider == "openai":`,
    `        return ChatOpenAI(model=target_model, temperature=temperature)`,
    `    else:`,
    `        raise RuntimeError(`,
    `            "No LLM provider available or configured. Set GOOGLE_API_KEY (Gemini) or OPENAI_API_KEY (OpenAI)."`,
    `        )`,
    ``,
  ];
  return lines.join('\n');
}

/**
 * Generate a single Agent node function.
 * @param {object} params
 * @param {string} params.fnName - Python function name (snake_case)
 * @param {string} params.id - Agent ID
 * @param {string|null} params.model - Model string
 * @param {number} params.temperature - Numeric temperature
 * @param {string|null} params.provider - Provider ('gemini'|'openai'|null)
 * @param {string} params.escapedInstructions - Triple-quote escaped instructions
 * @param {string[]} params.inputs - Array of input variable names
 * @param {string[]} params.outputs - Array of output variable names
 * @returns {string}
 */
export function generateAgentNodeTemplate({
  fnName,
  id,
  model,
  temperature,
  provider,
  escapedInstructions,
  inputs,
  outputs,
}) {
  const modelArg = model != null ? `"${model}"` : `None`;
  const providerArg = provider ? `"${provider}"` : `None`;
  const lines = [
    `def ${fnName}(state: WorkflowState) -> WorkflowState:`,
    `    """Agent: ${id}"""`,
    `    llm = get_llm(model=${modelArg}, temperature=${temperature}, provider=${providerArg})`,
    ``,
    `    system_prompt = """${escapedInstructions}"""`,
    ``,
  ];

  if (inputs && inputs.length > 0) {
    lines.push(`    # Collect input from state`);
    lines.push(`    user_parts = []`);
    for (const input of inputs) {
      lines.push(`    if state.get("${input}") is not None:`);
      lines.push(`        user_parts.append(f"${input}: {state['${input}']}")`);
    }
    lines.push(`    user_message = "\\n".join(user_parts) if user_parts else "No input provided."`);
  } else {
    lines.push(`    user_message = json.dumps({k: v for k, v in state.items() if v is not None})`);
  }

  lines.push(``);
  lines.push(`    messages = [`);
  lines.push(`        {"role": "system", "content": system_prompt},`);
  lines.push(`        {"role": "user", "content": user_message},`);
  lines.push(`    ]`);
  lines.push(``);
  lines.push(`    response = llm.invoke(messages)`);
  lines.push(`    result = response.content`);
  lines.push(``);

  if (outputs.length === 1) {
    lines.push(`    return {"${outputs[0]}": result}`);
  } else if (outputs.length > 1) {
    lines.push(`    # Attempt to parse structured output for multiple output fields`);
    lines.push(`    try:`);
    lines.push(`        parsed = json.loads(result)`);
    lines.push(`        updates = {}`);
    for (const output of outputs) {
      lines.push(`        if "${output}" in parsed:`);
      lines.push(`            updates["${output}"] = parsed["${output}"]`);
    }
    lines.push(`        return updates`);
    lines.push(`    except (json.JSONDecodeError, TypeError):`);
    lines.push(`        # Fallback: assign raw result to first output field`);
    lines.push(`        return {"${outputs[0]}": result}`);
  } else {
    lines.push(`    return {}`);
  }

  lines.push(``);
  lines.push(``);
  return lines.join('\n');
}

/**
 * Generate the build_graph() function.
 * @param {object} params
 * @param {Array<{ id: string, fnName: string }>} params.nodes
 * @param {string} params.entrypoint
 * @param {Array<{ source: string, target: string }>} params.edges
 * @param {string[]} params.terminals
 * @returns {string}
 */
export function generateGraphBuilderTemplate({ nodes, entrypoint, edges, terminals }) {
  const lines = [
    `# ─── Graph Construction ──────────────────────────────────────────────────────`,
    ``,
    `def build_graph() -> StateGraph:`,
    `    """Build and compile the LangGraph workflow."""`,
    `    graph = StateGraph(WorkflowState)`,
    ``,
    `    # Register agent nodes`,
  ];

  for (const node of nodes) {
    lines.push(`    graph.add_node("${node.id}", ${node.fnName})`);
  }
  lines.push(``);

  lines.push(`    # Set entry point`);
  lines.push(`    graph.set_entry_point("${entrypoint}")`);
  lines.push(``);

  if (edges && edges.length > 0) {
    lines.push(`    # Add edges between agents`);
    for (const edge of edges) {
      lines.push(`    graph.add_edge("${edge.source}", "${edge.target}")`);
    }
    lines.push(``);
  }

  lines.push(`    # Connect terminal nodes to END`);
  for (const terminal of terminals) {
    lines.push(`    graph.add_edge("${terminal}", END)`);
  }
  lines.push(``);
  lines.push(`    return graph.compile()`);
  lines.push(``);
  return lines.join('\n');
}

/**
 * Generate the __main__ execution block.
 * @param {object} params
 * @param {string} params.workflowName
 * @param {Array<{ name: string, defaultVal: string }>} params.initialStateFields
 * @returns {string}
 */
export function generateMainTemplate({ workflowName, initialStateFields, requiredFields = [] }) {
  const lines = [
    `# ─── Execution ──────────────────────────────────────────────────────────────`,
    ``,
    `if __name__ == "__main__":`,
    `    if hasattr(sys.stdout, 'reconfigure'):`,
    `        sys.stdout.reconfigure(encoding='utf-8')`,
    `    # Ensure at least one API key is set`,
    `    if not _LLM_PROVIDER:`,
    `        print("Error: No LLM provider configured.")`,
    `        print("  Set GOOGLE_API_KEY (Gemini, preferred) or OPENAI_API_KEY (OpenAI).")`,
    `        print("  Example: export GOOGLE_API_KEY='your-key-here'")`,
    `        exit(1)`,
    ``,
    `    print(f"Using LLM provider: {_LLM_PROVIDER}")`,
    `    app = build_graph()`,
    ``,
    `    # Initial state — populate input fields before running`,
    `    initial_state: WorkflowState = {`,
  ];

  for (const field of initialStateFields) {
    lines.push(`        "${field.name}": ${field.defaultVal},`);
  }

  lines.push(`    }`);
  lines.push(``);
  lines.push(`    # Override initial_state from --input / -i file or OAF_INPUT_FILE if provided at runtime`);
  lines.push(`    input_file = os.environ.get("OAF_INPUT_FILE")`);
  lines.push(`    args = sys.argv[1:]`);
  lines.push(`    for idx in range(len(args)):`);
  lines.push(`        if args[idx] in ("--input", "-i") and idx + 1 < len(args):`);
  lines.push(`            input_file = args[idx + 1]`);
  lines.push(`            break`);
  lines.push(`        elif args[idx].startswith("--input="):`);
  lines.push(`            input_file = args[idx].split("=")[1]`);
  lines.push(`            break`);
  lines.push(`        elif args[idx].startswith("-i="):`);
  lines.push(`            input_file = args[idx].split("=")[1]`);
  lines.push(`            break`);
  lines.push(``);
  lines.push(`    if input_file:`);
  lines.push(`        try:`);
  lines.push(`            with open(input_file, "r", encoding="utf-8") as f:`);
  lines.push(`                runtime_input = json.load(f)`);
  lines.push(`                if isinstance(runtime_input, dict):`);
  lines.push(`                    initial_state.update(runtime_input)`);
  lines.push(`        except Exception as err:`);
  lines.push(`            print(f"Error reading input file '{input_file}': {err}", file=sys.stderr)`);
  lines.push(`            sys.exit(1)`);
  lines.push(``);
  
  if (requiredFields && requiredFields.length > 0) {
    lines.push(`    # Validate required state variables`);
    lines.push(`    missing_required = [`);
    lines.push(`        f for f in ${JSON.stringify(requiredFields)}`);
    lines.push(`        if initial_state.get(f) is None or (isinstance(initial_state.get(f), str) and initial_state.get(f) == "")`);
    lines.push(`    ]`);
    lines.push(`    if missing_required:`);
    lines.push(`        print(f"Error: Missing required state variables: {', '.join(missing_required)}", file=sys.stderr)`);
    lines.push(`        sys.exit(1)`);
    lines.push(``);
  }

  lines.push(`    print(f"Running workflow: ${workflowName}")`);
  lines.push(`    print(f"{'-' * 50}")`);
  lines.push(``);
  lines.push(`    result = app.invoke(initial_state)`);
  lines.push(``);
  lines.push(`    print(f"{'-' * 50}")`);
  lines.push(`    print("Workflow completed. Final state:")`);
  lines.push(`    print(json.dumps(result, indent=2, default=str))`);
  lines.push(``);

  return lines.join('\n');
}
