"""
OpenAgentFlow — Generated LangGraph Workflow

Workflow: Code Review Loop
Generated by: OpenAgentFlow Compiler v0.1.5

This file was auto-generated from an .oaf workflow definition.
Do not edit manually — regenerate from the source .oaf file.
"""

import os
import sys
import json
import operator
from typing import Annotated, Optional, TypedDict

from langgraph.graph import StateGraph, END

# ─── Environment Variable Hierarchy ──────────────────────────────────────────
def _load_env_hierarchy():
    """Load environment variables from local .env and ~/.oaf/.env if not already set."""
    def parse_env_file(path):
        if not os.path.exists(path):
            return {}
        res = {}
        try:
            with open(path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#") or "=" not in line:
                        continue
                    k, v = line.split("=", 1)
                    k, v = k.strip(), v.strip()
                    if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
                        v = v[1:-1]
                    res[k] = v
        except Exception:
            pass
        return res

    local_path = os.path.join(os.getcwd(), ".env")
    global_path = os.path.join(os.path.expanduser("~"), ".oaf", ".env")

    local_env = parse_env_file(local_path)
    global_env = parse_env_file(global_path)

    for k, v in local_env.items():
        if k not in os.environ:
            os.environ[k] = v
    for k, v in global_env.items():
        if k not in os.environ:
            os.environ[k] = v

_load_env_hierarchy()

# LLM providers — Gemini, OpenAI, Anthropic
_LLM_PROVIDER = None
try:
    from langchain_google_genai import ChatGoogleGenerativeAI
    if os.environ.get("GOOGLE_API_KEY"):
        _LLM_PROVIDER = "gemini"
except ImportError:
    pass

try:
    from langchain_openai import ChatOpenAI
    if os.environ.get("OPENAI_API_KEY") and _LLM_PROVIDER is None:
        _LLM_PROVIDER = "openai"
except ImportError:
    pass

try:
    from langchain_anthropic import ChatAnthropic
    if os.environ.get("ANTHROPIC_API_KEY") and _LLM_PROVIDER is None:
        _LLM_PROVIDER = "anthropic"
except ImportError:
    pass

# ─── State Schema ───────────────────────────────────────────────────────────

class WorkflowState(TypedDict, total=False):
    code_snippet: Optional[str]  # @required
    review_feedback: Optional[str]
    status: Optional[str]
    retry_count: Annotated[Optional[int], operator.add]

# ─── LLM Helper ─────────────────────────────────────────────────────────────

def get_llm(model: Optional[str] = "gemma-4-26b-a4b-it", temperature: float = 0.7, provider: Optional[str] = None):
    """Get the LLM instance. Uses provided model directly; falls back to OAF_DEFAULT_MODEL or raises error."""
    target_model = model if model else os.environ.get("OAF_DEFAULT_MODEL")
    override_model = os.environ.get("OAF_OVERRIDE_MODEL")
    if override_model:
        target_model = override_model
        provider = None

    if not target_model:
        raise RuntimeError(
            "No model specified and no default model configured. "
            "Please specify a 'model' property in your .oaf agent definition or set the OAF_DEFAULT_MODEL environment variable."
        )

    target_provider = provider
    if not target_provider and target_model:
        if target_model.startswith("claude-"):
            target_provider = "anthropic"
        elif target_model.startswith("gpt-") or target_model.startswith("o1") or target_model.startswith("o3"):
            target_provider = "openai"
        elif target_model.startswith("gemini-") or target_model.startswith("gemma-"):
            target_provider = "gemini"
    if not target_provider:
        target_provider = _LLM_PROVIDER

    if target_provider == "gemini":
        try:
            _cls = globals().get("ChatGoogleGenerativeAI")
            if _cls is None:
                from langchain_google_genai import ChatGoogleGenerativeAI as _cls
            inst = _cls(model=target_model, temperature=temperature)
            inst._oaf_provider = "gemini"
            return inst
        except ImportError:
            raise RuntimeError("Missing package: pip install langchain-google-genai")
    elif target_provider == "openai":
        try:
            _cls = globals().get("ChatOpenAI")
            if _cls is None:
                from langchain_openai import ChatOpenAI as _cls
            inst = _cls(model=target_model, temperature=temperature)
            inst._oaf_provider = "openai"
            return inst
        except ImportError:
            raise RuntimeError("Missing package: pip install langchain-openai")
    elif target_provider == "anthropic":
        try:
            _cls = globals().get("ChatAnthropic")
            if _cls is None:
                from langchain_anthropic import ChatAnthropic as _cls
            inst = _cls(model=target_model, temperature=temperature)
            inst._oaf_provider = "anthropic"
            return inst
        except ImportError:
            raise RuntimeError("Missing package: pip install langchain-anthropic")
    else:
        raise RuntimeError(
            "No LLM provider available or configured. Run 'npx openagentflow auth' to set up credentials, or set GOOGLE_API_KEY / OPENAI_API_KEY / ANTHROPIC_API_KEY in your local .env file."
        )

def _parse_llm_output(raw_content, outputs):
    """Cleanly parse LLM content (string or list of thinking/text blocks) into state updates."""
    if isinstance(raw_content, list):
        text_parts = []
        for block in raw_content:
            if isinstance(block, dict):
                if block.get("type") == "text" or "text" in block:
                    text_parts.append(str(block.get("text", "")))
            elif isinstance(block, str):
                text_parts.append(block)
        result_text = "\n".join(text_parts).strip()
    else:
        result_text = str(raw_content).strip()

    clean_text = result_text
    if clean_text.startswith("```"):
        lines = clean_text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        clean_text = "\n".join(lines).strip()

    if len(outputs) == 1:
        out_key = outputs[0]
        try:
            parsed = json.loads(clean_text)
            if isinstance(parsed, dict) and out_key in parsed:
                return {out_key: parsed[out_key]}
        except Exception:
            pass
        return {out_key: result_text}
    elif len(outputs) > 1:
        target_text = clean_text
        if not (target_text.startswith("{") and target_text.endswith("}")):
            start_idx = target_text.find("{")
            end_idx = target_text.rfind("}")
            if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
                target_text = target_text[start_idx:end_idx + 1]
        try:
            parsed = json.loads(target_text)
            if isinstance(parsed, dict):
                updates = {}
                for out_key in outputs:
                    if out_key in parsed:
                        updates[out_key] = parsed[out_key]
                if updates:
                    return updates
        except Exception:
            pass
        import re
        updates = {}
        for out_key in outputs:
            pattern = re.compile("""(?:^|\n)[ \t]*[-*]?[ \t]*(?:["'])?""" + re.escape(out_key) + """(?:["'])?[ \t]*[:=][ \t]*(.+)""", re.IGNORECASE)
            match = pattern.search(clean_text)
            if match:
                val_str = match.group(1).strip()
                try:
                    updates[out_key] = json.loads(val_str)
                except Exception:
                    if val_str.isdigit() or (val_str.startswith("-") and val_str[1:].isdigit()):
                        updates[out_key] = int(val_str)
                    elif val_str.lower() in ("true", "false"):
                        updates[out_key] = (val_str.lower() == "true")
                    else:
                        updates[out_key] = val_str
        if updates:
            return updates
        return {outputs[0]: result_text}
    else:
        return {}

def reviewer_node(state: WorkflowState) -> WorkflowState:
    """Agent: Reviewer"""
    llm = get_llm(model="gemma-4-26b-a4b-it", temperature=0.7, provider="gemini")
    print(f'[Reviewer] Running agent (model="gemma-4-26b-a4b-it", provider={getattr(llm, "_oaf_provider", "unknown")})')

    system_prompt = """Review the following Python code snippet.
If the code is correct, efficient, and well-documented, set status to 'approved' and review_feedback to 'Looks good'.
If there are issues, set status to 'rejected' and provide specific review_feedback on what to fix.
Respond with valid JSON matching the output variables.\n\nIMPORTANT: You must respond ONLY with a valid JSON object containing exactly these fields: status, review_feedback. Do not include any other text, markdown, or commentary outside the JSON object."""

    # Collect input from state
    user_parts = []
    if state.get("code_snippet") is not None:
        user_parts.append(f"code_snippet: {state['code_snippet']}")
    user_message = "\n".join(user_parts) if user_parts else "No input provided."

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message},
    ]

    response = llm.invoke(messages)
    return _parse_llm_output(response.content, ["status","review_feedback"])


def fixer_node(state: WorkflowState) -> WorkflowState:
    """Agent: Fixer"""
    llm = get_llm(model="gemma-4-26b-a4b-it", temperature=0.7, provider="gemini")
    print(f'[Fixer] Running agent (model="gemma-4-26b-a4b-it", provider={getattr(llm, "_oaf_provider", "unknown")})')

    system_prompt = """Fix the Python code based on the review_feedback.
Output the updated code_snippet.
Always output retry_count as 1 (this will increment the total count).
Respond with valid JSON matching the output variables.\n\nIMPORTANT: You must respond ONLY with a valid JSON object containing exactly these fields: code_snippet, retry_count. Do not include any other text, markdown, or commentary outside the JSON object."""

    # Collect input from state
    user_parts = []
    if state.get("code_snippet") is not None:
        user_parts.append(f"code_snippet: {state['code_snippet']}")
    if state.get("review_feedback") is not None:
        user_parts.append(f"review_feedback: {state['review_feedback']}")
    user_message = "\n".join(user_parts) if user_parts else "No input provided."

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message},
    ]

    response = llm.invoke(messages)
    return _parse_llm_output(response.content, ["code_snippet","retry_count"])


# ─── Graph Construction ──────────────────────────────────────────────────────

def build_graph() -> StateGraph:
    """Build and compile the LangGraph workflow."""
    graph = StateGraph(WorkflowState)

    # Register agent nodes
    graph.add_node("Reviewer", reviewer_node)
    graph.add_node("Fixer", fixer_node)

    # Set entry point
    graph.set_entry_point("Reviewer")

    # Add edges between agents
    def route_Reviewer(state: WorkflowState) -> str:
        if ((state.get("status") == "rejected") and (state.get("retry_count") < 3)): return "Fixer"
        if ((state.get("status") == "approved") or (state.get("retry_count") >= 3)): return END
        raise ValueError(f"No matching conditional edge from 'Reviewer'")
    graph.add_conditional_edges("Reviewer", route_Reviewer)

    graph.add_edge("Fixer", "Reviewer")
    return graph.compile()

# ─── Execution ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')
    # Ensure at least one API key is set
    if not _LLM_PROVIDER:
        print("Error: No LLM provider configured.")
        print("  Run 'npx openagentflow auth' to configure credentials or edit your local .env file.")
        print("  Or set manually: export GOOGLE_API_KEY='AIza...'")
        exit(1)

    print(f"Default fallback provider: {_LLM_PROVIDER}")
    app = build_graph()

    # Initial state — populate input fields before running
    initial_state: WorkflowState = {
        "code_snippet": None,
        "review_feedback": "",
        "status": "",
        "retry_count": 0,
    }

    # Override initial_state from --input / -i file or OAF_INPUT_FILE if provided at runtime
    input_file = os.environ.get("OAF_INPUT_FILE")
    args = sys.argv[1:]
    for idx in range(len(args)):
        if args[idx] in ("--input", "-i") and idx + 1 < len(args):
            input_file = args[idx + 1]
            break
        elif args[idx].startswith("--input="):
            input_file = args[idx].split("=")[1]
            break
        elif args[idx].startswith("-i="):
            input_file = args[idx].split("=")[1]
            break

    if input_file:
        try:
            with open(input_file, "r", encoding="utf-8") as f:
                runtime_input = json.load(f)
                if isinstance(runtime_input, dict):
                    initial_state.update(runtime_input)
        except Exception as err:
            print(f"Error reading input file '{input_file}': {err}", file=sys.stderr)
            sys.exit(1)

    # Validate required state variables
    missing_required = [
        f for f in ["code_snippet"]
        if initial_state.get(f) is None or (isinstance(initial_state.get(f), str) and initial_state.get(f) == "")
    ]
    if missing_required:
        print(f"Error: Missing required state variables: {', '.join(missing_required)}", file=sys.stderr)
        sys.exit(1)

    print(f"Running workflow: Code Review Loop")
    print(f"{'-' * 50}")

    result = app.invoke(initial_state)

    print(f"{'-' * 50}")
    print("Workflow completed. Final state:")
    print(json.dumps(result, indent=2, default=str))
